### ISSUE TITLE
Readme cleanup

### ISSUE THREAD

**Issue by juancampa** [cwlowder/hyper-orama#22]
Some files that shouldn't be there

 - `test.txt`
 - *.gif

@cjoshmartin

**Comment by lpulley** [comment]
The `demo-in.gif` and `demo-out.gif` files need to be there.

**Comment by cjoshmartin** [comment]
Also new details of how to install our package using NPM

**Comment by rioam2** [comment]
There's actually a really cool trick where you can drag&drop an image or gif into the composition window of a New Issue post and it will then upload that image to GitHub and provide you some markdown with the link that you can copy&paste into a readme, etc. This is really handy for publicly hosting https compliant images and using them elsewhere.

I can address this as well as issue #28 and submit a PR before we release as suggested in #61

**Comment by cjoshmartin** [comment]
@TejasQ @TejasQ We need update how to install our plugin as well

**Comment by cjoshmartin** [comment]
Fixed it in #65
