### ISSUE TITLE
Improved demo video

### ISSUE THREAD

**Issue by juancampa** [cwlowder/hyper-orama#28]
Demo video looks pretty great but there could be improvements:

 - Faster typing
 - Font size proportional to the frame
 - Smaller dimensions
 - Higher resolution

**Comment by lpulley** [comment]
Do you think it matters whether the GIF at the top of the [README](https://github.com/cwlowder/hyper-orama/blob/master/README.md) is the same output of the GIF at the bottom (showing what it looks like to record)? Not sure if that would be confusing.

**Comment by juancampa** [comment]
GIF at the bottom serves a different purpose. I'd just leave it as is, or make a smaller, faster, to the point one.
