### ISSUE TITLE
npm package name

### ISSUE THREAD

**Issue by styfle** [cwlowder/hyper-orama#44]
Are the two hyphens intentional?

https://www.npmjs.com/package/hyper-orama

vs

https://www.npmjs.com/package/hyper--orama

**Comment by cwlowder** [comment]
@cjoshmartin Created the npm package

**Comment by lpulley** [comment]
It was a result of some rate-limiting issue, I believe? Is that something we can change now?

**Comment by cjoshmartin** [comment]
@styfle  What @lpulley said. I am working with npm `hyper-orama` back online https://www.npmjs.com/package/hyper-orama

**Comment by lpulley** [comment]
@cjoshmartin So we can close this without any changes as long as they give you the name back?

**Comment by cjoshmartin** [comment]
@lpulley We have it now, I will upload it after I get out of my class.

**Comment by cjoshmartin** [comment]
Don't close this issue until then

**Comment by cjoshmartin** [comment]
#48 is the PR for this
