### ISSUE TITLE
Fix Mac path to now executable

### ISSUE THREAD

**Issue by cwlowder** [cwlowder/hyper-orama#50]
The path to use for `now` is incorrect on Mac. This needs to be fixed before we can release.

**Comment by cwlowder** [comment]
@lpulley @cjoshmartin @rioam2 How are we going to fix this issue? Who has access to a mac?

**Comment by lpulley** [comment]
I don't have a Mac. Don't know anyone with one, either.

**Comment by rioam2** [comment]
I dont have a mac either, or know anyone who could test it out for us. If I remember correctly, the binary for now should be relative to ./node_modules/.bin (?)

**Comment by cwlowder** [comment]
>I dont have a mac either, or know anyone who could test it out for us. If I remember correctly, the 
>binary for now should be relative to ./node_modules/.bin (?)

I tried that on Windows, but it kept braking for me. So I/someone changed it to the current implementation. If anyone owns a Mac and can test/fix this, I will be forever grateful.

**Comment by kmui2** [comment]
The current path `node_modules/now/download/dist/now` and `node_modules/.bin/now` both work for Mac.

**Comment by kmui2** [comment]
Using the `.bin` directory should be the most reliable.

**Comment by cwlowder** [comment]
> Using the .bin directory should be the most reliable.

@kmui2 
For my Hyper it didn't work. But! If I use `./node_modules/.bin/now.cmd` then it works on windows. Perhaps we can use `now.cmd` on windows and `now` on everything else with some logic?

 I also created a ticket for an issue I discovered when I changed the path to now #56

**Comment by cjoshmartin** [comment]
@cwlowder what shell are you running again?

**Comment by kmui2** [comment]
@cwlowder I added a couple of changes to account for the `now.cmd` in my branch `path-fix`. Could you check whether it works for you?

**Comment by cwlowder** [comment]
> @cwlowder I added a couple of changes to account for the `now.cmd` in my branch `path-fix`. Could you check whether it works for you?

@kmui2 
```
events.js:182 Uncaught Error: spawn C:\Users\Pita\.hyper_plugins\local\hyper-orama\node_modules\now\download\dist\now.cmd ENOENT
    at exports._errnoException (util.js:1024)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192)
    at onErrorNT (internal/child_process.js:374)
    at _combinedTickCallback (internal/process/next_tick.js:138)
    at process._tickCallback (internal/process/next_tick.js:180)
```

I have no idea what happened, but that directory(C:\Users\Pita\.hyper_plugins\local\hyper-orama\node_modules\now\download\dist) now only has:
```
index.js  now  now.exe
```
now.exe appears to work for windows. Could you try that?

**Comment by kmui2** [comment]
> ```
> index.js  now  now.exe
> ```
> now.exe appears to work for windows. Could you try that?

I only get `index.js` and `now`. I've pushed another change that switches to using the `node_modules/.bin` directory. Could you try that?

**Comment by cwlowder** [comment]
@kmui2 Works like a charm!
