### ISSUE TITLE
How to getting the plugin running again?

### ISSUE THREAD

**Issue by cjoshmartin** [cwlowder/hyper-orama#53]
* I changed directories into hyper
* typed `yarn build` 
* `yarn run app`
* check if our plugin in was in `~/.hyper_plugins/local/`
* I tried to press `control-option-r` and nothing happened

**Comment by cwlowder** [comment]
Do you have a .hyper.js file in the root of your hyper directory? That changes the location of local plugins from `~/.hyper_plugins/local/` to `my_repo/.hyper_plugins/local/`
