### ISSUE TITLE
Have video match Hyper's branding/style

### ISSUE THREAD

**Issue by rioam2** [cwlowder/hyper-orama#57]
Following recommendation from @rauchg, the recording output should match the branding of Hyper, as seen on the official website as such: 

![Hyper Branding](https://i.gyazo.com/d0dd77240fd8acac26901acfbaca43f5.png)

I'm planning to do some work on getting the frame code cleaned up and matching this example. Any other suggestions are welcome!

**Comment by cwlowder** [comment]
It might not be good to do now, but in future I would like to give users 4-5 different options for pre-made frames/styles and eventually the ability to use their own frame. However, I would like #45 to be finished first for that.

**Comment by rioam2** [comment]
> It might not be good to do now, but in future I would like to give users 4-5 different options for pre-made frames/styles and eventually the ability to use their own frame. However, I would like #45 to be finished first for that.

That's a good idea. I've extracted the frame Markup into its own file in #58 so this could be completely feasible.
